# Generated by Django 2.2.6 on 2021-10-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_auto_20191214_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
