# Generated by Django 2.2.6 on 2021-12-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_passenger_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asehi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField(null=True)),
                ('bus_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='book_ticket',
            old_name='date',
            new_name='date2',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='date',
            new_name='date1',
        ),
    ]
