# Generated by Django 2.2.6 on 2021-10-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_auto_20191214_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='asehi',
            name='date3',
            field=models.DateField(null=True),
        ),
    ]
