# Generated by Django 2.2.6 on 2021-10-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_passenger_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_route',
            name='route',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book_ticket',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.Passenger'),
        ),
        migrations.AlterField(
            model_name='book_ticket',
            name='route',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
