# Generated by Django 2.2.6 on 2021-10-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_book_ticket_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
