# Generated by Django 2.2.6 on 2021-10-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_passenger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='route',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
