# Generated by Django 2.2.6 on 2021-10-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_passenger_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_bus',
            name='arrivaltime',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='add_bus',
            name='departuretime',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
